# =================================================================================================
#
#	Starling Framework
#	Copyright 2011-2014 Gamua. All Rights Reserved.
#
#	This program is free software. You can redistribute and/or modify it
#	in accordance with the terms of the accompanying license agreement.
#
# =================================================================================================

git: 
    depth: 10

language: objective-c

env:
    - TERM=dumb

before_script:
    # Update Brew silently
    - brew update >brew-update.log
    # Install Brew Packages silently
    - brew install ant gradle adobe-air-sdk >brew-install.log
    # Adobe Flash Player for CLI
    - brew install caskroom/cask/brew-cask
    - brew cask install flash-player-debugger
    # Set env. variable used by FlexUnit
    - export FLASHPLAYER_DEBUGGER="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"
    # Set env. variable used by Gradle
    - export FLASH_PLAYER_EXE="$HOME/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"
    # Apache Flex SDK
    - wget -O flex_sdk.zip http://mirrors.gigenet.com/apache/flex/4.13.0/binaries/apache-flex-sdk-4.13.0-bin.zip
    - unzip -q flex_sdk.zip -d flex_sdk
    # Init PlayerGlobals
    - echo env.PLAYERGLOBAL_HOME=libs/player > flex_sdk/env.properties
    # Init Apache Flex SDK
    - mkdir -p flex_sdk/frameworks/libs/player/11.1/
    - mkdir -p flex_sdk/frameworks/libs/player/15.0/
    - cp -f /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/15.0/playerglobal.swc flex_sdk/frameworks/libs/player/11.1/
    - cp -f /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/15.0/playerglobal.swc flex_sdk/frameworks/libs/player/15.0/
    # Set env. variable used by Ant and Gradle
    - export FLEX_HOME="$TRAVIS_BUILD_DIR/flex_sdk"
    # Init Adobe AIR SDK
    - mkdir -p /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/11.1/
    - cp -f /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/15.0/playerglobal.swc /usr/local/opt/adobe-air-sdk/libexec/frameworks/libs/player/11.1/
    # Set env. variable used by Ant and Gradle
    - export AIR_HOME="/usr/local/opt/adobe-air-sdk/libexec"
    # permissions
    - chmod +x flex_sdk/bin/mxmlc

script:
    - cd starling/build/ant && ant
    - cd ../gradle && gradle